server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:h2:mem:sewagealert_auth
    driver-class-name: org.h2.Driver
    username: root
    password: NewRoot@123

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app:
  jwt:
    secret: c2V3YWdlLWFsZXJ0LWh5ZGVyYWJhZC1zZWNyZXQta2V5LWZvci1qd3QtdG9rZW4tZ2VuZXJhdGlvbi0yMDI2
    expiration-ms: 86400000
  admin:
    name: Administrator
    email: admin@sewagealert.com
    password: Admin@123
  field-officers:
    accounts:
      - name: Ravi Kumar
        email: ravi.officer@sewagealert.com
        password: Officer@123
      - name: Suresh Reddy
        email: suresh.officer@sewagealert.com
        password: Officer@123
      - name: Anil Sharma
        email: anil.officer@sewagealert.com
        password: Officer@123

logging:
  level:
    com.sewagealert.auth: DEBUG
    org.springframework.security: INFO